### ISSUE TITLE
Can't show rectangle of a single day

### ISSUE THREAD

**Issue by inodb** [cBioPortal/clinical-timeline#5]
Sometimes one would like to display a duration of a single day. Only way that is possible now is by using a circle

**Comment by ritikakundra** [comment]
What if we add a day to day long durations?

**Comment by inodb** [comment]
I actually fixed this one already. It is at https://github.com/inodb/clinical-timeline/commit/f4198da68ab0ba3097d73d3c682b649f2db8e9ca. Just haven't pushed the changes yet to cbioportal/clinical-timeline. The square looks like this:
![screen shot 2015-07-14 at 11 22 02 am](https://cloud.githubusercontent.com/assets/1334004/8676981/9440c3f0-2a1a-11e5-94f5-c197e7b61042.png)

**Comment by inodb** [comment]
Fixed in https://github.com/cBioPortal/clinical-timeline/commit/f4198da68ab0ba3097d73d3c682b649f2db8e9ca
