### ISSUE TITLE
Do not combine y/d/m on x-axis, instead pick one

### ISSUE THREAD

**Issue by inodb** [cBioPortal/clinical-timeline#57]
Currently we show time from diagnosis on the x axis with year/month/days combined. E.g.:

![screen shot 2016-03-02 at 3 17 38 pm](https://cloud.githubusercontent.com/assets/1334004/13473996/fd850ef4-e089-11e5-8876-a8cf292b5311.png)

The common practice for clinical timelines is to stick to one of y/m/d and express every x label as that one element. So in the example above, it would be better to stick to months only. That is the first tick would be -16m (round down starting day), the last tick 1m (round up starting day). That way the interval between the ticks is always equal, which also a little easier on the eyes.

Also note that depending on what time the period spans, the ticks should be different. If the timeline only spans a couple of days use days, several months use months, several years use years. This is what the function `getZoomLevel` is for.

**Comment by madhug-nadig** [comment]
#60

**Comment by madhug-nadig** [comment]
#60

**Comment by rohangoel96** [comment]
[#61](https://github.com/cBioPortal/clinical-timeline/pull/61)

**Comment by madhug-nadig** [comment]
Made a new commit based on what @rohangoel96 has already done.
